### ISSUE TITLE
scrubbing fails with: An error occurred deploying ALBA proxy ovs-albaproxy_myvpool02_ovs-node02-1604_scrub

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#1178]
```
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/scheduledtask.py", line 310, in execute_scrub_work
    client.dir_chmod(scrub_directory, 0777)  # Celery task executed by 'ovs' user and should be able to write in it
  File "/opt/OpenvStorage/ovs/extensions/generic/sshclient.py", line 367, in dir_chmod
    self.run(['chmod', recursive_str, str(oct(mode)), directory])
  File "/opt/OpenvStorage/ovs/extensions/generic/sshclient.py", line 59, in inner_function
    return outer_function(self, *args, **kwargs)
  File "/opt/OpenvStorage/ovs/extensions/generic/sshclient.py", line 286, in run
    .format(command, output, error))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 22: ordinal not in range(128)
```

**Comment by khenderick** [comment]
\u2019 is some kind of single right quote. Most likely the systems used are for whatever reason using fancy markup.

Let's use `.encode('ascii', 'replace')` on unicode after we replaced the most common entries (and let's add \u2019 to that list).

**Comment by khenderick** [comment]
Fixed by #1182, packaged in openvstorage-2.7.6-rev.4323.a37c7f7
Manual code sync by openvstorage/alba-asdmanager#162 packaged in openvstorage-sdm-1.6.6-rev.449.77bd347

**Comment by kinvaris** [comment]
FAILED:

We still see the issue occuring. 
```
In [2]: ScheduledTaskController.execute_scrub()
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-2-865121fa4fdc> in <module>()
----> 1 ScheduledTaskController.execute_scrub()

/usr/lib/python2.7/dist-packages/celery/local.pyc in __call__(self, *a, **kw)
    186 
    187     def __call__(self, *a, **kw):
--> 188         return self._get_current_object()(*a, **kw)
    189 
    190     def __len__(self):

/usr/lib/python2.7/dist-packages/celery/app/task.pyc in __call__(self, *args, **kwargs)
    418             if self.__self__ is not None:
    419                 return self.run(self.__self__, *args, **kwargs)
--> 420             return self.run(*args, **kwargs)
    421         finally:
    422             self.pop_request()

/opt/OpenvStorage/ovs/lib/helpers/decorators.pyc in new_function(*args, **kwargs)
    179 
    180                 try:
--> 181                     output = function(*args, **kwargs)
    182                     log_message('Task {0} finished successfully'.format(task_name))
    183                     return output

/opt/OpenvStorage/ovs/lib/scheduledtask.pyc in execute_scrub()
    268 
    269         if len(error_messages) > 0:
--> 270             raise Exception('Errors occurred while scrubbing:\n  - {0}'.format('\n  - '.join(error_messages)))
    271 
    272     @staticmethod

Exception: Errors occurred while scrubbing:
  - Scrubber - vPool myvpool02 - StorageRouter ovs-node03-1604 - An error occurred deploying ALBA proxy ovs-albaproxy_myvpool02_ovs-node03-1604_scrub
  - Scrubber - vPool myvpool02 - StorageRouter ovs-node02-1604 - An error occurred deploying ALBA proxy ovs-albaproxy_myvpool02_ovs-node02-1604_scrub
  - Scrubber - vPool myvpool02 - StorageRouter ovs-node03-1604 - vDisk integration-tests-scrubbing-3 - Scrubbing failed
  - Scrubber - vPool myvpool02 - StorageRouter ovs-node03-1604 - vDisk integration-tests-scrubbing-0 - Scrubbing failed
  - Scrubber - vPool myvpool02 - StorageRouter ovs-node03-1604 - vDisk integration-tests-scrubbing-2 - Scrubbing failed
  - Scrubber - vPool myvpool02 - StorageRouter ovs-node03-1604 - vDisk integration-tests-scrubbing-4 - Scrubbing failed
```

But this time with this error:
```
2016-11-22 11:07:04 26400 +0100 - ovs-node01-1604 - 11358/140605963732736 - extensions/sshclient - 18 - ERROR - Command "'chmod' '' '0777' '/mnt/hdd3/scrub_work_myvpool02_ovs-node02-1604'" failed with output "" and error "chmod: invalid mode: ''
```

**Comment by khenderick** [comment]
Fixed somewhat related-ish issue by #1188, packaged in openvstorage-2.7.6-rev.4327.b5617a3

**Comment by kinvaris** [comment]
PASSED based on CI tests: http://testrail.cloudfounders.com/index.php?/plans/view/34898
